### ISSUE TITLE
Ideal `pathParams` implementation

### ISSUE THREAD

**Issue by maxdeviant** [maxdeviant/peregrine#1]
I'd like to nail down the implementation of `pathParams` to something better than the current implementation.

The design of the API I want seems like it might be rather complex (or perhaps even impossible) to  implement.

## State of the World

Currently `pathParams` is defined like so:

```purs
pathParams :: forall params. String -> (Map String String -> Maybe params) -> (params -> Handler) -> Handler
pathParams path' parseParams next req = do
  -- ...
```

Using `pathParams` looks like this:

```purs
-- 1. Define a params type.
type UserParams
  = { id :: String }

-- 2. Write a parsing function.
parseUserParams :: Map String String -> Maybe UserParams
parseUserParams params = do
  id <- params # Map.lookup "id"
  pure { id }

userHandler :: UserParams -> Handler
userHandler { id } req = do
  -- ...

-- 3. Pass the parsing function to `pathParams`.
pathParams "/<id>" parseUserParams userHandler
```

## Ideal API

```purs
-- 1. Define a params type.
--    Note: This probably has to be a `newtype` so we can define a type class instance.
newtype UserParams
  = UserParams
  { firstName :: String
  , lastName :: String
  , age :: Int
  }

-- 2. Define/derive a type class for the params type.
--   - Do we need to use generics in order to derive?
--   - Ideally we should be able to derive if all of the record's fields have values
--     that have a `FromParam` instance.
-- This probably isn't valid PureScript.
derive instance fromParamsUserParams :: FromParams UserParams

userHandler :: UserParams -> Handler
userHandler (UserParams { firstName, lastName, age }) req = do
  -- ...

-- 3. Call `pathParams` without needing to supply an explicit parsing function.
pathParams "<firstName>/<lastName>/<age>" userHandler
```

## Alternative API

An alternative API that I've been thinking about would be to do position-based parameters that all have a `FromParam` instance:

```purs
-- 1. Define a handler parameterized using types with `FromParam` instances.
userHandler :: String -> String -> Int -> Handler
userHandler firstName lastName age req = do
  -- ...

-- 2. Call `pathParamsN` with the parameterized handler.
--    We'll need to define a bunch of versions of `pathParams with different arities
--    to support a reasonable number of parameters.
pathParams3 "<firstName>/<lastName>/<age>" userHandler
```

**Comment by maxdeviant** [comment]
At a high level `pathParams` works like so:
- Takes the input route (e.g., `"<firstName>/<lastName>/<age>"`)
- Creates a regular expression to match all values enclosed in `<` `>` as capture groups
- Matches the incoming request path against the regular expression
- If the path does not match, bail out
- If the path does match, try to construct the `params` from the matches
- If the construction of `params` fails, bail out
- If the construction of `params` succeeds, call the handler with `params`

The open questions I have are:
- Is there a way we can take the matches from the regular expression and use them to construct a PureScript record?
- Can we constrain the polymorphic `params` to be a record whose values all satisfy `FromParam`?

**Comment by maxdeviant** [comment]
Some prior art (courtesy of Nate Faubion):
- https://github.com/justinwoo/purescript-kushikatsu
- https://github.com/justinwoo/purescript-kushiyaki
- https://github.com/justinwoo/purescript-la-galbi
- https://github.com/natefaubion/purescript-routing-duplex

**Comment by maxdeviant** [comment]
As of 3f951a6a2b494388f6779f7b7bf3399b39569fce we now have a working version of the alternative API described above, so I think we're going to roll with that for now and see how it goes.

**Comment by mikesol** [comment]
One idea is to combine 2 & 3 by using the same approach used in the Barlow-lens library. That is, you'd implement a lightweight string parser at the type-level and use it to parse the path and extract the values. Then you could have ie:

```purescript
myPath (Proxy :: _ "/foo/<id>/bar/<orders>") { id: idHandler, orders: ordersHandler }
```
And it'd be typesafe via fundeps.
